export const COMENZAR_DESCARGA_RESTAURANTE = "COMENZAR_DESCARGA_RESTAURANTE";
export const DESCARGA_RESTAURANTE_EXITO = "DESCARGA_RESTAURANTE_EXITO";
export const DESCARGA_RESTAURANTE_ERROR = "DESCARGA_RESTAURANTE_ERROR";

export const ACTUALIZAR_RESTAURANTE = "ACTUALIZAR_RESTAURANTE";
export const ACTUALIZAR_RESTAURANTE_EXITO = "ACTUALIZAR_RESTAURANTE_EXITO";
export const ACTUALIZAR_RESTAURANTE_ERROR = "ACTUALIZAR_RESTAURANTE_ERROR";

//Categorias
export const AGREGAR_CATEGORIA = "AGREGAR_CATEGORIA";
export const AGREGAR_CATEGORIA_EXITO = "AGREGAR_CATEGORIA_EXITO";
export const AGREGAR_CATEGORIA_ERROR = "AGREGAR_CATEGORIA_ERROR";

export const COMENZAR_DESCARGA_CATEGORIAS = "COMENZAR_DESCARGA_CATEGORIAS";
export const DESCARGAR_CATEGORIAS_EXITO = "DESCARGAR_CATEGORIAS_EXITO";
export const DESCARGAR_CATEGORIAS_ERROR = "DESCARGAR_CATEGORIAS_ERROR";

export const OBTENER_CATEGORIA_ELIMINAR = "OBTENER_CATEGORIA_ELIMINAR";
export const ELIMINAR_CATEGORIA_EXITO = "ELIMINAR_CATEGORIA_EXITO";
export const ELIMINAR_CATEGORIA_ERROR = "ELIMINAR_CATEGORIA_ERROR";

export const OBTENER_CATEGORIA_EDITAR = "OBTENER_CATEGORIA_EDITAR";
export const COMENZAR_CATEGORIA_EDITAR = "COMENZAR_CATEGORIA_EDITAR";
export const EDITAR_CATEGORIA_EXITO = "EDITAR_CATEGORIA_EXITO";
export const EDITAR_CATEGORIA_ERROR = "EDITAR_CATEGORIA_ERROR";

//Productos
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGAR_PRODUCTOS_EXITO = "DESCARGAR_PRODUCTOS_EXITO";
export const DESCARGAR_PRODUCTOS_ERROR = "DESCARGAR_PRODUCTOS_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const COMENZAR_PRODUCTO_EDITAR = "COMENZAR_PRODUCTO_EDITAR";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";

//Mesas 
export const AGREGAR_MESA = "AGREGAR_MESA";
export const AGREGAR_MESA_EXITO = "AGREGAR_MESA_EXITO";
export const AGREGAR_MESA_ERROR = "AGREGAR_MESA_ERROR";

export const COMENZAR_DESCARGA_MESAS = "COMENZAR_DESCARGA_MESAS";
export const DESCARGAR_MESAS_EXITO = "DESCARGAR_MESAS_EXITO";
export const DESCARGAR_MESAS_ERROR = "DESCARGAR_MESAS_ERROR";

export const OBTENER_MESA_ELIMINAR = "OBTENER_MESA_ELIMINAR";
export const ELIMINAR_MESA_EXITO = "ELIMINAR_MESA_EXITO";
export const ELIMINAR_MESA_ERROR = "ELIMINAR_MESA_ERROR";

export const OBTENER_MESA_EDITAR = "OBTENER_MESA_EDITAR";
export const COMENZAR_MESA_EDITAR = "COMENZAR_MESA_EDITAR";
export const EDITAR_MESA_EXITO = "EDITAR_MESA_EXITO";
export const EDITAR_MESA_ERROR = "EDITAR_MESA_ERROR";

//pedidos
export const OBTENER_NUMERO_ITEMS_PEDIDO = "OBTENER_NUMERO_ITEMS_PEDIDO";

export const COMENZAR_AGREGAR_PEDIDO = "COMENZAR_AGREGAR_PEDIDO";
export const AGREGAR_PEDIDO_EXITO = "AGREGAR_PEDIDO_EXITO";
export const AGREGAR_PEDIDO_ERROR = "AGREGAR_PEDIDO_ERROR";

export const COMENZAR_DESCARGA_PEDIDOS_PREPARAR = "COMENZAR_DESCARGA_PEDIDOS_PREPARAR";
export const DESCARGA_PEDIDOS_PREPARAR_EXITO = "DESCARGA_PEDIDOS_PREPARAR_EXITO";
export const DESCARGA_PEDIDOS_PREPARAR_ERROR = "DESCARGA_PEDIDOS_PREPARAR_ERROR";

export const COMENZAR_DESCARGA_PEDIDOS_ENTREGAR = "COMENZAR_DESCARGA_PEDIDOS_ENTREGAR";
export const DESCARGA_PEDIDOS_ENTREGAR_EXITO = "DESCARGA_PEDIDOS_ENTREGAR_EXITO";
export const DESCARGA_PEDIDOS_ENTREGAR_ERROR = "DESCARGA_PEDIDOS_ENTREGAR_ERROR";

//live para añadir pedido
export const AGREGAR_PEDIDO_LIVE = "AGREGAR_PEDIDO_LIVE";
export const AGREGAR_DETALLE_LIVE = "AGREGAR_DETALLE_LIVE";
//live para añadir pedido a entregar y quitar pedido de preparar
export const AGREGAR_PEDIDO_ENTREGAR_LIVE = "AGREGAR_PEDIDO_ENTREGAR_LIVE";
export const AGREGAR_DETALLE_ENTREGAR_LIVE = "AGREGAR_DETALLE_ENTREGAR_LIVE";
//live para quitar pedido de preparar despues de marcar como cancelado
export const QUITAR_PEDIDO_PREPARAR_LIVE = "QUITAR_PEDIDO_PREPARAR_LIVE";
export const QUITAR_DETALLE_PREPARAR_LIVE = "QUITAR_DETALLE_PREPARAR_LIVE";
//live para quitar pedido de entregar
export const QUITAR_PEDIDO_ENTREGAR_LIVE = "QUITAR_PEDIDO_ENTREGAR_LIVE";
export const QUITAR_DETALLE_ENTREGAR_LIVE = "QUITAR_DETALLE_ENTREGAR_LIVE";


export const COMENZAR_DESCARGA_TODOS_PEDIDOS = "COMENZAR_DESCARGA_TODOS_PEDIDOS";
export const DESCARGA_TODOS_PEDIDOS_EXITO = "DESCARGA_TODOS_PEDIDOS_EXITO";
export const DESCARGA_TODOS_PEDIDOS_ERROR = "DESCARGA_TODOS_PEDIDOS_ERROR";

//editar pedidos
export const COMENZAR_EDITAR_PEDIDO = "COMENZAR_EDITAR_PEDIDO";
export const EDITAR_PEDIDO_EXITO = "EDITAR_PEDIDO_EXITO";
export const EDITAR_PEDIDO_ERROR = "EDITAR_PEDIDO_ERROR";

//usuario login y registro
export const INICIAR_REGISTRO_USUARIO = "INICIAR_REGISTRO_USUARIO";
export const REGISTRO_USUARIO_EXITOSO = "REGISTRO_USUARIO_EXITOSO";
export const REGISTRO_USUARIO_ERROR = "REGISTRO_USUARIO_ERROR";
////
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const OBTENER_USUARIO_EXITO = "OBTENER_USUARIO_EXITO";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";
///
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
//descragar usuarios
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGA_USUARIIOS_EXITO = "DESCARGA_USUARIIOS_EXITO";
export const DESCARGA_USUARIIOS_ERROR = "DESCARGA_USUARIIOS_ERROR";
//
export const OBTENER_USUARIO_EDITAR = "OBTENER_USUARIO_EDITAR";
export const COMENZAR_USUARIO_EDITAR = "COMENZAR_USUARIO_EDITAR";
export const EDITAR_USUARIO_EXITO = "EDITAR_USUARIO_EXITO";
//eitar usuario logeado exito 
export const EDITAR_USUARIO_LOGEADO_EXITO = "EDITAR_USUARIO_LOGEADO_EXITO";
export const EDITAR_USUARIO_ERROR = "EDITAR_USUARIO_ERROR";

export const CERRAR_SESION = "CERRAR_SESION";

//datos de factuiracion
export const COMENZAR_DESCARGA_DATOSFACTURACION = "COMENZAR_DESCARGA_DATOSFACTURACION";
export const DESCARGA_DATOSFACTURACION_EXITO = "DESCARGA_DATOSFACTURACION_EXITO";
export const DESCARGA_DATOSFACTURACION_ERROR = "DESCARGA_DATOSFACTURACION_ERROR";

//insertar dtos fact
export const COMENZAR_INSERTAR_DATOSFACTURACION = "COMENZAR_INSERTAR_DATOSFACTURACION";
export const INSERTAR_DATOSFACTURACION_EXITO = "INSERTAR_DATOSFACTURACION_EXITO";
export const INSERTAR_DATOSFACTURACION_ERROR = "INSERTAR_DATOSFACTURACION_ERROR";
//decsragra pedidos x usuario
export const COMENZAR_DESCARGA_PEDIDOS_USUARIO = "COMENZAR_DESCARGA_PEDIDOS_USUARIO";
export const DESCARGA_PEDIDOS_USUARIO_EXITO = "DESCARGA_PEDIDOS_USUARIO_EXITO";
export const DESCARGA_PEDIDOS_USUARIO_ERROR = "DESCARGA_PEDIDOS_USUARIO_ERROR";
//agregar pedido enviado a mi state
export const AGREGAR_PEDIDO_STATE = "AGREGAR_PEDIDO_STATE";
export const AGREGAR_DETALLE_STATE = "AGREGAR_DETALLE_STATE";
