export const COMENZAR_DESCARGA_RESTAURANTE = "COMENZAR_DESCARGA_RESTAURANTE";
export const DESCARGA_RESTAURANTE_EXITO = "DESCARGA_RESTAURANTE_EXITO";
export const DESCARGA_RESTAURANTE_ERROR = "DESCARGA_RESTAURANTE_ERROR";

export const ACTUALIZAR_RESTAURANTE = "ACTUALIZAR_RESTAURANTE";
export const ACTUALIZAR_RESTAURANTE_EXITO = "ACTUALIZAR_RESTAURANTE_EXITO";
export const ACTUALIZAR_RESTAURANTE_ERROR = "ACTUALIZAR_RESTAURANTE_ERROR";

//Categorias
export const AGREGAR_CATEGORIA = "AGREGAR_CATEGORIA";
export const AGREGAR_CATEGORIA_EXITO = "AGREGAR_CATEGORIA_EXITO";
export const AGREGAR_CATEGORIA_ERROR = "AGREGAR_CATEGORIA_ERROR";

export const COMENZAR_DESCARGA_CATEGORIAS = "COMENZAR_DESCARGA_CATEGORIAS";
export const DESCARGAR_CATEGORIAS_EXITO = "DESCARGAR_CATEGORIAS_EXITO";
export const DESCARGAR_CATEGORIAS_ERROR = "DESCARGAR_CATEGORIAS_ERROR";

export const OBTENER_CATEGORIA_ELIMINAR = "OBTENER_CATEGORIA_ELIMINAR";
export const ELIMINAR_CATEGORIA_EXITO = "ELIMINAR_CATEGORIA_EXITO";
export const ELIMINAR_CATEGORIA_ERROR = "ELIMINAR_CATEGORIA_ERROR";

export const OBTENER_CATEGORIA_EDITAR = "OBTENER_CATEGORIA_EDITAR";
export const COMENZAR_CATEGORIA_EDITAR = "COMENZAR_CATEGORIA_EDITAR";
export const EDITAR_CATEGORIA_EXITO = "EDITAR_CATEGORIA_EXITO";
export const EDITAR_CATEGORIA_ERROR = "EDITAR_CATEGORIA_ERROR";

//Productos
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGAR_PRODUCTOS_EXITO = "DESCARGAR_PRODUCTOS_EXITO";
export const DESCARGAR_PRODUCTOS_ERROR = "DESCARGAR_PRODUCTOS_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const COMENZAR_PRODUCTO_EDITAR = "COMENZAR_PRODUCTO_EDITAR";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";

//Mesas 
export const AGREGAR_MESA = "AGREGAR_MESA";
export const AGREGAR_MESA_EXITO = "AGREGAR_MESA_EXITO";
export const AGREGAR_MESA_ERROR = "AGREGAR_MESA_ERROR";

export const COMENZAR_DESCARGA_MESAS = "COMENZAR_DESCARGA_MESAS";
export const DESCARGAR_MESAS_EXITO = "DESCARGAR_MESAS_EXITO";
export const DESCARGAR_MESAS_ERROR = "DESCARGAR_MESAS_ERROR";

export const OBTENER_MESA_ELIMINAR = "OBTENER_MESA_ELIMINAR";
export const ELIMINAR_MESA_EXITO = "ELIMINAR_MESA_EXITO";
export const ELIMINAR_MESA_ERROR = "ELIMINAR_MESA_ERROR";

export const OBTENER_MESA_EDITAR = "OBTENER_MESA_EDITAR";
export const COMENZAR_MESA_EDITAR = "COMENZAR_MESA_EDITAR";
export const EDITAR_MESA_EXITO = "EDITAR_MESA_EXITO";
export const EDITAR_MESA_ERROR = "EDITAR_MESA_ERROR";

